---
name: Add issues to project board

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/add-to-project@85100f0a11dfca7ddd8ee9d9a3a23a8cec060a02 # v0
        with:
          project-token: ${{ secrets.PROJECT_PAT }}
