---
name: Add issues to project board

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/add-to-project@f8ebad3dad09f2cd5caa8cbe2cc11beceebe711d # v0
        with:
          project-token: ${{ secrets.PROJECT_PAT }}
