---
name: Deploy

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  build-and-deploy:
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/jekyll@7193f2d6fda65de74a0d750fd19f53314f899200 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ruby-version: "3.3"
