---
name: Deploy

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  build-and-deploy:
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/jekyll@c97ca7c448df211268616ce438777228fe103733 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ruby-version: "4.0"
