---
name: Link Check Built Pages

on:
  schedule:
    - cron: 0 9 1 * *
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@dd42b32e779552c6f911ca469111449a410facff # v0
        with:
          branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
