---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@f8ebad3dad09f2cd5caa8cbe2cc11beceebe711d # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
