---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@85100f0a11dfca7ddd8ee9d9a3a23a8cec060a02 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml

      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/vale@85100f0a11dfca7ddd8ee9d9a3a23a8cec060a02 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
